knpu_oauth2_client:
    clients:
        keycloak:
            type: keycloak
            client_id: symfony6-app
            client_secret: '%env(KEYCLOAK_CLIENT_SECRET)%'
            auth_server_url: 'http://localhost:8080'
            realm: 'multiframework-sso'
            redirect_route: connect_keycloak_check
            redirect_params: {}