security:
    providers:
        app_user_provider:
            id: App\Security\KeycloakUserProvider

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\KeycloakAuthenticator

            logout:
                path: app_logout
                target: app_login



    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }